import styled from '@emotion/styled';
import { Link } from 'react-router-dom'

export const Header = styled.header`
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:block;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:15px;
  height:81px;
  line-height:21.4286px;
  margin-bottom:30px;
  text-size-adjust:100%;
  width:930px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBar = styled.div`
  background-color:rgb(44, 62, 80);
  border-bottom-color:rgba(0, 0, 0, 0);
  border-bottom-left-radius:0px;
  border-bottom-right-radius:0px;
  border-bottom-style:solid;
  border-bottom-width:0px;
  border-image-outset:0px;
  border-image-repeat:stretch;
  border-image-slice:100%;
  border-image-source:none;
  border-image-width:1;
  border-left-color:rgba(0, 0, 0, 0);
  border-left-style:solid;
  border-left-width:0px;
  border-right-color:rgba(0, 0, 0, 0);
  border-right-style:solid;
  border-right-width:0px;
  border-top-color:rgba(0, 0, 0, 0);
  border-top-left-radius:0px;
  border-top-right-radius:0px;
  border-top-style:solid;
  border-top-width:0px;
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:block;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:15px;
  height:60px;
  line-height:21.4286px;
  margin-bottom:21px;
  min-height:60px;
  position:relative;
  text-size-adjust:100%;
  width:930px;
  z-index:1000;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`

export const Container = styled.div`
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:inline;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:15px;
  height:60px;
  line-height:21.4286px;
  margin-left:9.29688px;
  margin-right:9.3125px;
  padding-left:15px;
  padding-right:15px;
  text-size-adjust:100%;
  width:911.391px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const Branding = styled.div`
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:block;
  float:left;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:15px;
  height:60px;
  line-height:21.4286px;
  margin-left:0px;
  margin-right:0px;
  min-height:1px;
  padding-left:15px;
  padding-right:15px;
  position:relative;
  text-size-adjust:100%;
  width:172.516px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const BrandingLink = styled(Link)`
  background-color:rgba(0, 0, 0, 0);
  box-sizing:border-box;
  color:rgb(255, 255, 255);
  cursor:pointer;
  display:block;
  float:left;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:19px;
  height:60px;
  line-height:19px;
  margin-left:-15px;
  padding-bottom:19.5px;
  padding-left:15px;
  padding-right:15px;
  padding-top:19.5px;
  text-decoration-color:rgb(255, 255, 255);
  text-decoration-line:none;
  text-decoration-style:solid;
  text-size-adjust:100%;
  width:157.516px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBarCollapse = styled.div`
  border-bottom-color:rgba(0, 0, 0, 0);
  border-left-color:rgba(0, 0, 0, 0);
  border-right-color:rgba(0, 0, 0, 0);
  border-top-color:rgba(0, 0, 0, 0);
  border-top-style:none;
  border-top-width:0px;
  box-shadow:none;
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:inline;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:15px;
  height:60px;
  line-height:21.4286px;
  margin-left:0px;
  margin-right:0px;
  overflow-x:visible;
  overflow-y:visible;
  padding-bottom:0px;
  padding-left:0px;
  padding-right:0px;
  text-size-adjust:100%;
  width:881.391px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBarList = styled.ul`
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:block;
  float:right;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:19px;
  height:60px;
  line-height:27.1428px;
  list-style-image:none;
  list-style-position:outside;
  list-style-type:none;
  margin-block-end:0px;
  margin-block-start:0px;
  margin-bottom:0px;
  margin-inline-end:-15px;
  margin-inline-start:0px;
  margin-left:0px;
  margin-right:-15px;
  margin-top:0px;
  padding-inline-start:0px;
  padding-left:0px;
  text-size-adjust:100%;
  width:326.906px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBarListItem = styled.li`
  box-sizing:border-box;
  color:rgb(44, 62, 80);
  display:block;
  float:left;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:19px;
  height:60px;
  line-height:27.1428px;
  list-style-image:none;
  list-style-position:outside;
  list-style-type:none;
  margin-bottom:0px;
  position:relative;
  text-align:left;
  text-size-adjust:100%;
  width:147.781px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBarListItemLink = styled(Link)`
  background-color:rgba(0, 0, 0, 0);
  box-sizing:border-box;
  color:rgb(255, 255, 255);
  cursor:pointer;
  display:block;
  font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size:19px;
  height:60px;
  line-height:21px;
  list-style-image:none;
  list-style-position:outside;
  list-style-type:none;
  padding-bottom:19.5px;
  padding-left:15px;
  padding-right:15px;
  padding-top:19.5px;
  position:relative;
  text-align:left;
  text-decoration-color:rgb(255, 255, 255);
  text-decoration-line:none;
  text-decoration-style:solid;
  text-size-adjust:100%;
  width:147.781px;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

export const NavBarListItemIcon = styled.i`
  box-sizing:border-box;
  color:rgb(255, 255, 255);
  cursor:pointer;
  display:inline-block;
  font-family:FontAwesome;
  font-size:19px;
  font-stretch:100%;
  font-style:normal;
  font-variant-caps:normal;
  font-variant-east-asian:normal;
  font-variant-ligatures:normal;
  font-variant-numeric:normal;
  font-weight:400;
  height:19px;
  line-height:19px;
  list-style-image:none;
  list-style-position:outside;
  list-style-type:none;
  margin-right:9px;
  text-align:left;
  text-rendering:auto;
  text-size-adjust:100%;
  width:17.6562px;
  -webkit-font-smoothing:antialiased;
  -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
`;

// export const NavBarListItemDropdown = styled.li`
//   box-sizing:border-box;
//   color:rgb(44, 62, 80);
//   display:block;
//   float:left;
//   font-family:Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
//   font-size:19px;
//   height:60px;
//   line-height:27.1428px;
//   list-style-image:none;
//   list-style-position:outside;
//   list-style-type:none;
//   margin-bottom:0px;
//   position:relative;
//   text-align:left;
//   text-size-adjust:100%;
//   width:65.9219px;
//   -webkit-tap-highlight-color:rgba(0, 0, 0, 0);
// `;
